'use client';
import {useState,useRef} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {parseCSV,mapInventory,csvFields} from '@/lib/projectos/csv';
export default function InventoryImport({projectId,currency,onComplete}:{projectId:string;currency:string;onComplete:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[rows,setRows]=useState<string[][]>([]),[mapping,setMapping]=useState<Record<string,number>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState('');const pending=useRef<{fingerprint:string;key:string}|null>(null);
 const preview=rows.length?mapInventory(rows,mapping,currency):{items:[],errors:[]};
 async function submit(){setBusy(true);setError('');try{const fingerprint=JSON.stringify({projectId,items:preview.items});if(pending.current?.fingerprint!==fingerprint)pending.current={fingerprint,key:crypto.randomUUID()};const res=await fetch('/api/os',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'command',command:{action:'inventory.import',key:pending.current.key,data:{projectId,rows:preview.items}}})});const body:any=await res.json();if(!res.ok)throw new Error(body.error);pending.current=null;setSaved(preview.items.length+' rows saved. New inventory is unreleased until reviewed.');setOpen(false);setRows([]);await onComplete()}catch(e){setError(e instanceof Error?e.message:'Import failed.')}finally{setBusy(false)}}
 return <><button className="btn" onClick={()=>setOpen(true)}>Import inventory CSV</button>{saved&&<p role="status" className="notice">{saved}</p>}<Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-[750px]"><DialogHeader><DialogTitle>Import inventory</DialogTitle><DialogDescription>Map columns, review errors, then confirm. Existing external IDs update unallocated items only; no partial import is saved.</DialogDescription></DialogHeader><label className="field">CSV file<input type="file" accept=".csv,text/csv" onChange={async e=>{setError('');try{const file=e.target.files?.[0];if(!file)return;const parsed=parseCSV(await file.text());setRows(parsed);setMapping(Object.fromEntries(csvFields.map(key=>[key,parsed[0].findIndex(h=>h.trim().toLowerCase()===key.toLowerCase())])))}catch(e){setRows([]);setError(e instanceof Error?e.message:'Invalid CSV.')}}}/></label>{rows.length>0&&<><div className="form-grid">{csvFields.map(key=><label className="field" key={key}>{key}<select value={mapping[key]??-1} onChange={e=>setMapping({...mapping,[key]:Number(e.target.value)})}><option value={-1}>Not mapped</option>{rows[0].map((header,i)=><option key={i} value={i}>{header}</option>)}</select></label>)}</div><p>{rows.length-1} rows · {currency} · prices in major units (480000.00)</p>{preview.errors.length>0?<div role="alert" className="error">{preview.errors.map(x=><p key={x}>{x}</p>)}</div>:<div className="notice">{preview.items.length} valid rows. Codes: {preview.items.slice(0,8).map(x=>String(x.code)).join(', ')}.</div>}<button className="btn primary" disabled={busy||!!preview.errors.length||!preview.items.length} onClick={submit}>{busy?'Importing…':'Confirm validated import'}</button></>}{error&&<p role="alert" className="error">{error}</p>}</DialogContent></Dialog></>;
}
