'use client';
import {Actor,RecordItem,money as formatMoney,nice,prettyDate} from '@/lib/projectos/domain';
import {ActionButton} from './ActionForm';

type Props={section:string;projectId:string;actor:Actor;records:RecordItem[];actors:Actor[];selected:string;onComplete:()=>Promise<void>};
export default function Operations({section,projectId,actor,records,actors,selected,onComplete}:Props){
 const money=(n:number)=>formatMoney(n,records.find(x=>x.id===projectId)?.data.currency||'CAD');const scoped=records.filter(x=>projectId==='all'||x.projectId===projectId);
 const act=(item:RecordItem,label:string,action:string)=><ActionButton label={label} action={action} context={{id:item.id,version:item.version,projectId:item.projectId,dealId:item.dealId,parentId:item.parentId}} records={records} actors={actors} onComplete={onComplete}/>;
 const create=(label:string,action:string,dealId?:string)=><ActionButton label={label} action={action} context={{projectId,dealId}} records={records} actors={actors} onComplete={onComplete}/>;
 const box=(title:string,children:React.ReactNode)=><section className="surface" style={{marginTop:20}}><div className="surface-head"><h2>{title}</h2></div><div className="surface-pad column">{children}</div></section>;
 if(section==='overview')return <>{['admin','manager'].includes(actor.role)&&box('Open task assignments',<>{scoped.filter(x=>x.kind==='task'&&x.status==='open').map(x=><div className="stat-line" key={x.id}><div><strong>{x.title}</strong><p className="muted small">{actors.find(a=>a.id===x.ownerId)?.name||'Unassigned'} · Due {prettyDate(x.data.dueAt)}</p></div>{act(x,'Assign / set deadline','task.assign')}</div>)}</>)}{box('My tasks',<>{scoped.filter(x=>x.kind==='task'&&x.ownerId===actor.id&&x.status==='open').map(x=><div className="stat-line" key={x.id}><div><strong>{x.title}</strong><p className="muted small">Due {prettyDate(x.data.dueAt)}</p></div>{act(x,'Mark complete','task.complete')}</div>)}</>)}{box('My notifications',<>{scoped.filter(x=>x.kind==='notification'&&x.ownerId===actor.id).map(x=><div className="stat-line" key={x.id}><span>{x.title} · {nice(x.status)}</span>{x.status==='unread'&&act(x,'Mark read','notification.read')}</div>)}</>)}</>;
 if(section==='sales')return <>{!selected&&box('Viewings & appointments',<>{['sales','manager','agent','delivery'].includes(actor.role)&&create('Request appointment','appointment.create')}{scoped.filter(x=>x.kind==='appointment').map(x=><div className="stat-line wrap" key={x.id}><div><strong>{x.title}</strong><p className="muted small">{prettyDate(x.data.startsAt)} · {x.data.resource} · {nice(x.status)}</p></div><div className="row wrap">{['sales','manager','delivery'].includes(actor.role)&&<>{x.status==='requested'&&act(x,'Confirm time','appointment.confirm')}{['requested','confirmed'].includes(x.status)&&act(x,'Record outcome','appointment.finish')}</>}</div></div>)}</>)}{!selected&&box('Project website requests',<>{scoped.filter(x=>x.kind==='request').map(x=><div className="stat-line" key={x.id}><div><strong>{x.title}</strong><p className="muted small">{nice(x.data.type)} · {x.data.email} · {x.status}</p></div><span className="pill">Does not reserve inventory</span></div>)}</>)}{selected&&records.some(x=>x.id===selected&&x.kind==='deal')&&box('Conversation',<>{scoped.filter(x=>x.kind==='message'&&x.dealId===selected).map(x=><article className="list-row" key={x.id}><div><strong>{x.data.authorName||x.title}</strong><p>{x.data.body}</p><small>{nice(x.data.audience)} · {prettyDate(x.createdAt)}</small></div></article>)}{create('Write a message','message.send',selected)}</>)}</>;
 if(section==='finance'&&actor.role==='finance')return <>{box('Finance actions',<>{scoped.filter(x=>x.kind==='refund'&&x.status==='approved').map(x=><div className="stat-line" key={x.id}><span>{x.title} · {money(x.data.amountCents)}</span>{act(x,'Record executed refund','refund.execute')}</div>)}{scoped.filter(x=>x.kind==='commission'&&['eligible','approved','partially_paid'].includes(x.status)).map(x=><div className="stat-line" key={x.id}><span>{x.title} · {money(x.data.amountCents)} · {nice(x.status)}</span>{x.status==='eligible'?act(x,'Approve commission','commission.approve'):act(x,'Record commission payment','commission.pay')}</div>)}{scoped.filter(x=>x.kind==='schedule'&&!x.data.dueAt).map(x=><div className="stat-line" key={x.id}><span>{x.title} · {money(x.data.amountCents)}</span>{act(x,'Confirm due date','schedule.due')}</div>)}<p className="notice">These actions record verified external bank movements. They never transfer funds.</p></>)}</>;
 return null;
}
