'use client';
import {Actor,RecordItem,nice} from '@/lib/projectos/domain';
import {ActionButton} from './ActionForm';
import InventoryImport from './InventoryImport';
export default function SetupPanel({section,projectId,actor,records,actors,onComplete}:{section:string;projectId:string;actor:Actor;records:RecordItem[];actors:Actor[];onComplete:()=>Promise<void>}){
 const p=records.find(x=>x.id===projectId&&x.kind==='project'),rows=records.filter(x=>x.projectId===projectId);
 const button=(label:string,action:string,item?:RecordItem)=><ActionButton label={label} action={action} context={{projectId,id:item?.id,version:item?.version,dealId:item?.dealId}} records={records} actors={actors} onComplete={onComplete}/>;
 let content:React.ReactNode=null;
 if(actor.role==='buyer'&&section==='finance')content=<>{rows.filter(x=>x.kind==='bank_account'&&x.status==='approved').map(x=><article key={x.id}><h3>{x.title}</h3><p style={{whiteSpace:'pre-wrap'}}>{x.data.instructions}</p></article>)}</>;
 if(section==='projects'&&['admin','manager'].includes(actor.role))content=<>{actor.role==='admin'&&button('Create project','project.create')}{actor.role==='manager'&&p&&<InventoryImport projectId={projectId} currency={p.data.currency} onComplete={onComplete}/>}</>;
 if(section==='sales'&&['sales','manager'].includes(actor.role))content=<>{button('Create deal & draft offer','deal.create')}{rows.filter(x=>x.kind==='lead'&&!['converted','lost'].includes(x.status)).map(x=><div key={x.id} className="stat-line"><span>{x.title} · {nice(x.status)}</span>{button('Update lead','lead.stage',x)}</div>)}{rows.filter(x=>x.kind==='request'&&x.status==='submitted').map(x=><div key={x.id} className="stat-line"><span>{x.title}</span>{button('Review request','request.review',x)}</div>)}</>;
 if(section==='administration'&&p)content=<>{actor.role==='admin'&&<><p>These people are sandbox roles, not invitations to real accounts.</p>{button('Add person & project grant','grant.create')}{button('Grant existing person this project','grant.restore')}{button('Change software payer','project.billing',p)}</>}{actor.role==='manager'&&<><p>Policy v{p.data.policyVersion}: {p.data.holdHours||24} hours · deposit {(p.data.depositBps??200)/100}% · milestone {(p.data.milestoneBps??1800)/100}%. Existing deals retain their version.</p>{button('Approve new policy version','project.policy',p)}</>}</>;
 if(section==='finance'&&actor.role==='finance')content=<>{button('Propose bank instructions','bank.propose')}{rows.filter(x=>x.kind==='bank_account').map(x=><div className="stat-line" key={x.id}><div><strong>{x.title}</strong><p>{nice(x.status)}</p><p>{x.data.instructions}</p></div>{x.status==='proposed'&&x.data.proposedBy!==actor.id&&button('Approve account','bank.approve',x)}</div>)}</>;
 if(section==='delivery'&&['delivery','manager'].includes(actor.role))content=<>{button('Create milestone','milestone.create')}{actor.role==='delivery'&&rows.filter(x=>x.kind==='change'&&['approved','ordered','implemented'].includes(x.status)).map(x=><div className="stat-line" key={x.id}><span>{x.title} · {nice(x.status)}</span>{button(x.status==='approved'?'Record order':x.status==='ordered'?'Record implementation':'Verify result',x.status==='approved'?'change.order':x.status==='ordered'?'change.implement':'change.verify',x)}</div>)}</>;
 if(section==='care'&&actor.role==='care')content=<>{rows.filter(x=>x.kind==='service'&&!['closed','declined'].includes(x.status)).map(x=><div className="stat-line" key={x.id}><span>{x.title} · {nice(x.status)}</span>{button(x.status==='on_hold'?'Resume case':'Pause with review date',x.status==='on_hold'?'service.resume':'service.pause',x)}</div>)}</>;
 return content?<section className="surface" style={{marginTop:20}}><div className="surface-head"><h2>{section==='projects'?'Project setup':'Workspace actions'}</h2></div><div className="surface-pad column">{content}</div></section>:null;
}
