import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import ts from 'typescript';
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'projectos-reports-'));
for(const name of ['domain','setup','engine','reports']){const source=fs.readFileSync(`lib/projectos/${name}.ts`,'utf8').replaceAll("from './domain'","from './domain.mjs'").replaceAll("from './setup'","from './setup.mjs'");fs.writeFileSync(path.join(temp,name+'.mjs'),ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText)}
const {seed}=await import(pathToFileURL(path.join(temp,'domain.mjs'))),{report,reportCSV}=await import(pathToFileURL(path.join(temp,'reports.mjs'))),{run}=await import(pathToFileURL(path.join(temp,'engine.mjs')));
const s=seed(),actor=id=>s.actors.find(x=>x.id===id),q=(kind,extra={})=>report(s,actor('manager'),{kind,projectId:'all',...extra});
assert.throws(()=>report(s,actor('buyer'),{kind:'receipts',projectId:'all'}),/restricted/);
const foreign=s.entities.find(x=>x.kind==='project'&&!actor('manager').projectIds.includes(x.id));assert.ok(foreign);assert.throws(()=>q('available',{projectId:foreign.id}),/unavailable/);
assert.ok(q('available').rows.every(x=>actor('manager').projectIds.includes(x.projectId)));
assert.throws(()=>q('receipts',{from:'2026-02-30'}),/valid date/);assert.throws(()=>q('receipts',{from:'2026-09-26',to:'2026-09-25'}),/precede/);
const payment=s.entities.find(x=>x.id==='payment-sam');assert.equal(q('receipts').unavailableDates,1);
payment.data.receivedAt='2026-09-25T23:59:59Z';payment.data.amountCents=400000;
s.entities.push({...structuredClone(payment),id:'second-payment',data:{...payment.data,amountCents:600000}});
s.entities.push({...structuredClone(payment),id:'refund-test',data:{...payment.data,amountCents:200000,direction:'refund'}});
s.entities.push({...structuredClone(payment),id:'euro-test',data:{...payment.data,amountCents:12345,currency:'EUR'}});
const r=q('receipts',{from:'2026-09-25',to:'2026-09-25'});assert.equal(r.count,4);assert.deepEqual(r.totals.CAD,{amountCents:800000,receiptsCents:1000000,refundsCents:200000});assert.equal(r.totals.EUR.amountCents,12345);assert.equal(q('receipts',{from:'2026-09-26'}).count,0);
const csv=reportCSV([{...r.rows[0],title:'=HYPERLINK("x")'}]);assert.ok(csv.includes("'="));assert.ok(!csv.includes('reference'));assert.ok(!csv.includes('confirmedBy'));
const task=s.entities.find(x=>x.kind==='task'&&x.status==='open'&&actor('manager').projectIds.includes(x.projectId));assert.ok(task);
const command={action:'task.assign',id:task.id,expectedVersion:task.version,key:crypto.randomUUID(),data:{actorId:'sales',dueAt:'2026-10-01T12:00:00Z',reason:'Coverage handoff'}};
const result=run(s,actor('manager'),command);const changed=result.state.entities.find(x=>x.id===task.id);assert.equal(changed.ownerId,'sales');assert.equal(changed.data.assignmentHistory.length,1);assert.equal(task.data.assignmentHistory,undefined);
assert.throws(()=>run(s,actor('sales'),command),/role/);
const outsider=s.actors.find(x=>!x.projectIds.includes(task.projectId));assert.ok(outsider);assert.throws(()=>run(s,actor('manager'),{...command,data:{...command.data,actorId:outsider.id}}),/existing valid grant/);
assert.throws(()=>run(result.state,result.state.actors.find(x=>x.id==='manager'),command),/changed/);
console.log('PASS: report isolation, UTC boundaries, currency separation, partial receipts/refunds, unknown-date warning, CSV safety, task access, history and stale writes.');
fs.rmSync(temp,{recursive:true,force:true});
