import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import ts from 'typescript';
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'projectos-setup-'));
for(const name of ['domain','setup','csv','engine']){const source=fs.readFileSync(`lib/projectos/${name}.ts`,'utf8').replace("from './domain'","from './domain.mjs'").replace("from './setup'","from './setup.mjs'");fs.writeFileSync(path.join(temp,name+'.mjs'),ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText)}
const {seed,access}=await import(pathToFileURL(path.join(temp,'domain.mjs'))),{run}=await import(pathToFileURL(path.join(temp,'engine.mjs'))),{parseCSV,mapInventory}=await import(pathToFileURL(path.join(temp,'csv.mjs')));
let s=seed();const item=id=>s.entities.find(x=>x.id===id),person=id=>s.actors.find(x=>x.id===id),call=(actor,action,id,data={})=>{const output=run(s,person(actor),{action,id,data,key:crypto.randomUUID(),expectedVersion:item(id)?.version});s=output.state;return output.id};
const project=call('admin','project.create',undefined,{title:'Test project',slug:'test-project',city:'Test city',currency:'EUR',timezone:'Europe/Bratislava',areaUnit:'m²'});
assert.equal(access(s,person('manager'),item(project)),false);
const originalGrant=structuredClone(item('grant-sales'));
for(const actorId of ['manager','sales','buyer','finance','finance-2','delivery'])call('admin','grant.restore',undefined,{projectId:project,actorId,reason:'Test approval'});
assert.deepEqual(item('grant-sales'),originalGrant,'Grant expansion must not mutate an older grant');
assert.equal(access(s,person('manager'),item(project)),true);
const parsed=parseCSV('externalId,code,type,price,area\r\nh1,"A,101",home,123456.78,70\r\np1,P1,parking,12000,0');
const {items,errors}=mapInventory(parsed,{externalId:0,code:1,type:2,price:3,area:4},'EUR');assert.equal(errors.length,0);assert.equal(items[0].priceCents,12345678);assert.equal(items[0].code,'A,101');assert.throws(()=>parseCSV('a,b\n"open,b'),/Unclosed/);
call('manager','inventory.import',undefined,{projectId:project,rows:items});const units=s.entities.filter(x=>x.kind==='inventory'&&x.projectId===project);assert.equal(units.length,2);assert.equal(units[0].status,'unreleased');
call('manager','inventory.import',undefined,{projectId:project,rows:items});assert.equal(s.entities.filter(x=>x.kind==='inventory'&&x.projectId===project).length,2);
const before=structuredClone(s);assert.throws(()=>call('manager','inventory.import',undefined,{projectId:project,rows:[...items,{...items[0],externalId:'bad',code:'new',priceCents:-1}]}),/Invalid/);assert.deepEqual(s,before);
for(const u of units)call('manager','inventory.release',u.id,{status:'released'});
const lead=call('sales','lead.create',undefined,{projectId:project,name:'Test buyer',email:'buyer@example.invalid',source:'Test'});
call('manager','project.policy',project,{holdHours:12,depositBps:500,milestoneBps:1500,reason:'Policy test'});
const deal=call('sales','deal.create',undefined,{leadId:lead,unitId:units[0].id,accessoryIds:[units[1].id],partyActorIds:['buyer'],sellerSignerId:'manager',expiresAt:new Date(Date.now()+86400000).toISOString()});assert.equal(item(deal).data.priceCents,13545678);
call('manager','project.policy',project,{holdHours:48,depositBps:1000,milestoneBps:1000,reason:'Future deals only'});
const offer=s.entities.find(x=>x.kind==='offer'&&x.dealId===deal);call('manager','offer.approve',offer.id);call('sales','hold.create',deal);
assert.equal(item(deal).data.policySnapshot.holdHours,12);assert.equal(item(deal).data.policyVersion,2);
const schedule=s.entities.filter(x=>x.kind==='schedule'&&x.dealId===deal);assert.equal(schedule.reduce((n,x)=>n+x.data.amountCents,0),13545678);assert(schedule.every(x=>x.data.currency==='EUR'));assert.equal(schedule.find(x=>x.data.gate==='reservation').data.amountCents,677283);
assert.throws(()=>call('manager','inventory.import',undefined,{projectId:project,rows:items}),/Allocated/);
const owner=item(project).data.ownerOrganizationId;call('admin','project.billing',project,{organizationId:'agency'});assert.equal(item(project).data.ownerOrganizationId,owner);assert.equal(access(s,person('agent-a'),item(project)),false);
const bank=call('finance','bank.propose',undefined,{projectId:project,title:'Test bank',instructions:'Fictional instructions',reason:'Test evidence'});assert.throws(()=>call('finance','bank.approve',bank),/second/);call('finance-2','bank.approve',bank);assert.equal(item(project).data.bankAccountId,bank);
const grant=s.entities.find(x=>x.kind==='grant'&&x.projectId===project&&x.data.actorId==='sales');call('admin','grant.revoke',grant.id);assert.equal(access(s,person('sales'),item(project)),false);assert.equal(access(s,person('sales'),item('cedar-quay')),true);
console.log('PASS project setup; immutable prior grants; scoped revocation; CSV parsing, atomic validation, stable-ID deduplication; arbitrary-price deal; frozen policy; exact EUR instalments; billing ownership separation; two-person bank approval.');fs.rmSync(temp,{recursive:true,force:true});
