import {State,Actor,RecordItem,Kind,Command,DomainError,find,access,allocations,balance} from './domain';
import {setup,setupActions} from './setup';
const bad=(msg:string,status=400):never=>{throw new DomainError(msg,status)};
const say=(v:any,label:string,max=500)=>{if(typeof v!=='string'||!v.trim()||v.length>max)bad(`${label} is required.`);return (v as string).trim()};
const pos=(v:any)=>{if(!Number.isSafeInteger(v)||v<=0||v>9000000000000)bad('Enter a valid positive amount.');return v as number};
const when=(v:any)=>{if(typeof v!=='string'||!Number.isFinite(Date.parse(v)))bad('Choose a valid date and time.');return new Date(v).toISOString()};
export function run(original:State,actor:Actor,command:Command,now=new Date().toISOString()):{state:State,id:string,message:string}{
 const s=structuredClone(original),a=s.actors.find(x=>x.id===actor.id&&x.active);if(!a)bad('Your access is no longer active.',403);
 if(setupActions.has(command.action))return setup(s,a!,command,now);
 const d=command.data||{},action=command.action;
 const role=(...roles:string[])=>{if(!roles.includes(a!.role))bad('Your role cannot perform this action.',403)};
 const get=(id:string,kind?:Kind,check=true):RecordItem=>{const e=find(s,id);if(!e||kind&&e.kind!==kind||check&&!access(s,a!,e))bad('Record not found or no longer accessible.',404);return e!};
 const project=(id:string)=>get(id,'project');
 const add=(kind:Kind,title:string,status:string,data:Record<string,any>,projectId:string,dealId?:string,ownerId?:string,parentId?:string)=>{const p=get(projectId,'project',false);const e:RecordItem={id:crypto.randomUUID(),kind,title,status,projectId,dealId,ownerId,parentId,organizationId:p.organizationId,version:1,createdAt:now,updatedAt:now,data};s.entities.push(e);return e};
 const bump=(e:RecordItem)=>{e.version++;e.updatedAt=now;return e};
 const task=(label:string,e:RecordItem,ownerId:string,days=1)=>{const p=get(e.projectId!,'project',false),requested=s.actors.find(x=>x.id===ownerId),owner=requested&&access(s,requested,p)?requested:s.actors.find(x=>x.active&&x.role===(requested?.role||ownerId)&&access(s,x,p));if(!owner)bad('Assign an active '+(requested?.role||ownerId)+' to this project before continuing.');return add('task',label,'open',{entityId:e.id,dueAt:new Date(Date.parse(now)+days*86400000).toISOString()},e.projectId!,e.dealId,owner!.id)};
 const rel=(e:RecordItem)=>get(e.kind==='deal'?e.id:e.dealId!,'deal',false);
 const items=(e:RecordItem)=>s.entities.filter(x=>x.kind==='allocation'&&x.dealId===e.id&&!x.data.endedAt);
 const due=(e:RecordItem,gate:string)=>s.entities.filter(x=>x.kind==='schedule'&&x.dealId===e.id&&x.status==='active'&&['reservation','completion'].includes(gate)&& (gate==='completion'||x.data.gate===gate)).some(x=>balance(s,x)>0);
 const risk=(e:RecordItem)=>s.entities.some(x=>x.dealId===e.id&&(x.kind==='document'&&['out_for_signature','partially_signed','fully_signed'].includes(x.status)||x.kind==='payment'&&x.status==='confirmed'));
 const termination=(e:RecordItem)=>s.entities.some(x=>x.kind==='termination'&&x.dealId===e.id&&!['released','withdrawn'].includes(x.status));
 const invalidate=(e:RecordItem)=>{if(e.status!=='completed'){e.data.financeApproval=null;e.data.legalCompletion=null;bump(e)}};
 const e=command.id?get(command.id):null as unknown as RecordItem;if(e&&command.expectedVersion!==undefined&&e.version!==command.expectedVersion)bad('Record changed. Reload and try again.',409);let output=e;
 switch(action){
 case 'request.create':{const p=project(d.projectId),unit=get(d.unitId,'inventory',false);if(unit.projectId!==p.id||unit.data.type!=='home')bad('Choose a home in this project.');if(!['interest','viewing','reservation'].includes(d.type))bad('Choose a request type.');if(d.type==='reservation'&&(unit.status!=='released'||allocations(s,unit.id)))bad('This home is no longer available for a reservation request.',409);const name=say(d.name,'Name',120),email=say(d.email,'Email',200).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))bad('Enter a valid email.');output=add('request',`${name} · ${unit.title}`,'submitted',{type:d.type,unitId:unit.id,email,source:'Demo project website',marketingConsent:!!d.marketingConsent,agentId:a!.role==='agent'?a!.id:null,description:String(d.message||'').slice(0,500)},p.id,undefined,'sales');task('Review new '+d.type+' request',output,'sales');break;}
 case 'lead.create':{role('sales','manager','agent');const p=project(d.projectId),name=say(d.name,'Name',120),email=say(d.email,'Email',200).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))bad('Enter a valid email address.');const dupe=s.entities.filter(x=>x.kind==='contact'&&x.organizationId===p.organizationId&&x.data.email===email);const c=add('contact',name,'active',{email,fictional:true},p.id,undefined,a!.id);output=add('lead',name,'new',{contactId:c.id,unitId:d.unitId||null,source:d.source||'Manual',nextStep:'Contact the buyer',marketingConsent:!!d.marketingConsent},p.id,undefined,a!.id);task('Contact '+name,output,a!.id);if(dupe.length)task('Review possible duplicate contact',output,'manager');break;}
 case 'lead.stage':{role('sales','manager','agent');if(e?.kind!=='lead')bad('Select a lead.');if(!['new','contacted','qualified','viewing','negotiating','lost'].includes(d.status))bad('This stage requires a confirmed reservation.');if(d.status==='lost')e.data.lostReason=say(d.reason,'Loss reason');e.status=d.status;e.data.nextStep=d.nextStep||e.data.nextStep;bump(e);break;}
 case 'offer.approve':{role('manager');if(e?.kind!=='offer'||e.status!=='draft')bad('Select a draft offer.');if(Date.parse(e.data.expiresAt)<=Date.parse(now))bad('Offer expired.');e.status='approved';e.data.approvedAt=now;e.data.approvedBy=a!.id;bump(e);break;}
 case 'hold.create':{role('sales','manager');if(e?.kind!=='deal'||!['draft','expired','released'].includes(e.status))bad('Select a new deal.');const offer=s.entities.filter(x=>x.kind==='offer'&&x.dealId===e.id&&x.status==='approved').at(-1);if(!offer||Date.parse(offer!.data.expiresAt)<=Date.parse(now))bad('Approve a current offer first.');for(const id of [...e.data.itemIds].sort()){const u=get(id,'inventory',false);if(u.projectId!==e.projectId||u.status!=='released'||allocations(s,id))bad('A home or accessory is unavailable.',409)}
 const policy=e.data.policySnapshot||{version:e.data.policyVersion,holdHours:24,depositBps:200,milestoneBps:1800};e.data.policySnapshot=structuredClone(policy);
 e.status='hold';e.data.holdExpiresAt=new Date(Math.min(Date.parse(now)+policy.holdHours*3600000,Date.parse(offer!.data.expiresAt))).toISOString();e.data.offerId=offer!.id;e.data.offerSnapshot=structuredClone(offer!.data);bump(e);
 for(const id of [...e.data.itemIds].sort())add('allocation',get(id,'inventory',false).title+' allocation','hold',{itemId:id,endedAt:null},e.projectId!,e.id);
 if(!s.entities.some(x=>x.kind==='schedule'&&x.dealId===e.id)){const total=BigInt(e.data.priceCents),deposit=Number(total*BigInt(policy.depositBps)/10000n),milestone=Number(total*BigInt(policy.milestoneBps)/10000n),rest=e.data.priceCents-deposit-milestone;for(const [title,value,gate,at] of [['Reservation deposit',deposit,'reservation',e.data.holdExpiresAt],['Construction milestone',milestone,'completion',null],['Completion balance',rest,'completion',null]] as const)if(value>0)add('schedule',title,'active',{amountCents:value,currency:e.data.currency,gate,dueAt:at},e.projectId!,e.id)}task('Verify reservation deposit',e,'finance');break;}
 case 'hold.extend':{role('manager');if(e?.kind!=='deal'||!['hold','review'].includes(e.status))bad('Select an active hold.');const end=when(d.expiresAt),offer=get(e.data.offerId,'offer',false);if(Date.parse(end)<=Date.parse(now)||Date.parse(end)>Date.parse(offer!.data.expiresAt))bad('Expiry must be in the future and within the approved offer.');say(d.reason,'Reason');if(e.status==='review'&&(!e.data.reviewLegal||!e.data.reviewFinance))bad('Legal and Finance reviews are required.');e.status='hold';e.data.holdExpiresAt=end;bump(e);break;}
 case 'hold.release':{role('sales','manager');if(e?.kind!=='deal'||!['hold','review'].includes(e.status))bad('Select a hold.');if(risk(e))bad('Signed material or a confirmed receipt requires a termination review.');say(d.reason,'Reason');e.status='released';bump(e);for(const x of items(e)){x.status='ended';x.data.endedAt=now;bump(x)}break;}
 case 'hold.review':{role('legal','finance');if(e?.kind!=='deal'||e.status!=='review')bad('This hold is not under review.');e.data[a!.role==='legal'?'reviewLegal':'reviewFinance']={at:now,actorId:a!.id,evidence:say(d.reason,'Review evidence')};bump(e);break;}
 case 'document.create':{role('sales','manager','legal','finance','delivery','care','buyer','contractor');const p=project(d.projectId);if(d.dealId&&a!.role!=='contractor'){const z=get(d.dealId,'deal');if(z.projectId!==p.id)bad('Wrong project.');if(a!.role==='buyer'&&!z.data.partyActorIds.includes(a!.id))bad('This is not your deal.',403)}if(a!.role==='contractor'){const j=get(d.parentId,'work_order');if(j.ownerId!==a!.id||j.dealId!==d.dealId||j.projectId!==p.id)bad('This job is not assigned to you.',403)}const audience=a!.role==='buyer'?'buyer':a!.role==='contractor'?'contractor':['buyer','agent','all_parties','internal','finance','legal','contractor'].includes(d.audience)?d.audience:'internal';output=add('document',say(d.title,'Document title'),'draft',{type:d.type||'evidence',audience,fileId:say(d.fileId,'File reference'),filename:say(d.filename,'File name'),mime:say(d.mime,'File type'),size:pos(d.size),sha256:say(d.sha256,'File fingerprint'),version:1,requiredSigners:d.type==='reservation_agreement'||d.type==='sale_agreement'?(get(d.dealId,'deal',false).data.requiredSigners||[]):[]},p.id,d.dealId,a!.id,d.parentId);break;}
 case 'document.review':case 'document.approve':{role('legal');if(e?.kind!=='document'||e.status!==(action==='document.review'?'draft':'in_review'))bad('Document is in the wrong stage.');e.status=action==='document.review'?'in_review':'approved';bump(e);break;}
 case 'document.signing':{role('legal');if(e?.kind!=='document'||e.status!=='approved')bad('Approve the document first.');const z=rel(e);if(!['hold','reserved','contracting'].includes(z.status)||!items(z).length||z.status==='hold'&&Date.parse(z.data.holdExpiresAt)<=Date.parse(now))bad('A live hold or reservation is required.');e.status='out_for_signature';e.data.signingStartedAt=now;bump(e);if(z.status==='reserved'){z.status='contracting';bump(z);for(const q of items(z)){q.status='contracting';bump(q)}}break;}
 case 'document.signature':{role('legal');if(e?.kind!=='document'||!['out_for_signature','partially_signed'].includes(e.status))bad('Document is not open for signing.');if(!e.data.requiredSigners.includes(d.signerId))bad('Person is not a required signer.');const proof=get(d.evidenceId,'document');if(proof.dealId!==e.dealId)bad('Evidence belongs to another deal.');if(s.entities.some(q=>q.kind==='signature'&&q.parentId===e.id&&q.data.signerId===d.signerId))bad('Signature already verified.');add('signature','Verified signature','verified',{signerId:d.signerId,evidenceId:proof.id,documentVersion:e.data.version,signedAt:when(d.signedAt),verifiedBy:a!.id},e.projectId!,e.dealId,a!.id,e.id);e.status=e.data.requiredSigners.every((id:string)=>s.entities.some(q=>q.kind==='signature'&&q.parentId===e.id&&q.data.signerId===id))?'fully_signed':'partially_signed';bump(e);break;}
 case 'document.cancel_signing':{role('legal');if(e?.kind!=='document'||!['out_for_signature','partially_signed'].includes(e.status))bad('No open signing.');e.status='cancelled';e.data.cancellationEvidence=say(d.reason,'Cancellation evidence');bump(e);break;}
 case 'payment.record':{role('buyer','finance');const z=get(d.dealId,'deal');if(d.projectId!==z.projectId||d.currency!==z.data.currency)bad('The deal or currency does not match.');const ref=say(d.reference,'Bank reference',100),accountId=project(z.projectId!).data.bankAccountId||'demo-account';if(s.entities.some(x=>x.kind==='payment'&&x.projectId===z.projectId&&x.data.reference===ref&&x.data.accountId===accountId))bad('Bank reference already recorded.');output=add('payment','Receipt · '+ref,'pending',{amountCents:pos(d.amountCents),currency:d.currency,reference:ref,accountId,bankVersion:project(z.projectId!).data.bankVersion||0,receivedAt:when(d.receivedAt),evidence:say(d.evidence,'Evidence'),direction:'receipt',submittedBy:a!.id},z.projectId!,z.id,a!.id);task('Verify receipt',output,'finance');break;}
 case 'payment.confirm':case 'payment.reject':{role('finance');if(e?.kind!=='payment'||e.status!=='pending')bad('Select a pending receipt.');e.status=action==='payment.confirm'?'confirmed':'rejected';e.data.reviewedBy=a!.id;e.data.review=say(d.reason,'Verification');bump(e);if(e.status==='confirmed'){invalidate(rel(e));if(['expired','released','terminated'].includes(rel(e).status))task('Review late payment',e,'finance',0)}break;}
 case 'payment.allocate':{role('finance');if(e?.kind!=='payment'||e.status!=='confirmed'||e.data.direction!=='receipt')bad('Select a verified receipt.');const line=get(d.scheduleId,'schedule'),n=pos(d.amountCents);if(line.dealId!==e.dealId||line.data.currency!==e.data.currency)bad('Instalment and receipt must belong to the same deal and currency.');const used=s.entities.filter(q=>q.kind==='payment_allocation'&&q.status==='active'&&q.data.paymentId===e.id).reduce((v,q)=>v+q.data.amountCents,0);if(n>balance(s,line)||n>e.data.amountCents-(e.data.refundedCents||0)-used)bad('Allocation exceeds the remaining balance.');output=add('payment_allocation','Receipt allocation','active',{paymentId:e.id,scheduleId:line.id,amountCents:n},e.projectId!,e.dealId,a!.id);invalidate(rel(e));break;}
 case 'payment.unallocate':{role('finance');if(e?.kind!=='payment_allocation'||e.status!=='active')bad('Select an allocation.');e.status='reversed';e.data.reversalReason=say(d.reason,'Correction reason');bump(e);invalidate(rel(e));break;}
 case 'schedule.due':{role('delivery','finance');if(e?.kind!=='schedule')bad('Select an instalment.');e.data.dueAt=when(d.dueAt);bump(e);break;}
 case 'reservation.confirm':{role('manager');if(e?.kind!=='deal'||e.status!=='hold'||Date.parse(e.data.holdExpiresAt)<=Date.parse(now))bad('A live hold is required.');if(!e.data.partyActorIds?.length||due(e,'reservation'))bad('Identify the buyers and verify the required reservation deposit.');if(!s.entities.some(x=>x.kind==='document'&&x.dealId===e.id&&x.data.type==='reservation_agreement'&&x.status==='fully_signed'))bad('A verified reservation agreement signed by every party is required.');if(items(e).length!==e.data.itemIds.length)bad('Inventory is incomplete.');e.status='reserved';e.data.reservedAt=now;bump(e);for(const q of items(e)){q.status='reserved';bump(q)}const lead=find(s,e.data.leadId);if(lead){lead.status='converted';bump(lead)}task('Prepare the sale agreement',e,'legal');break;}
 case 'deal.binding':{role('legal');if(e?.kind!=='deal'||!['reserved','contracting'].includes(e.status)||termination(e))bad('A current, unchallenged reservation is required.');if(!s.entities.some(x=>x.kind==='document'&&x.dealId===e.id&&x.data.type==='sale_agreement'&&x.status==='fully_signed'))bad('Verify every required sale agreement signature first.');e.data.binding={at:now,actorId:a!.id,evidence:say(d.reason,'Binding condition evidence'),policyVersion:e.data.policyVersion};e.status='committed';bump(e);for(const q of items(e)){q.status='committed';bump(q)}break;}
 case 'termination.request':{role('manager','legal');if(e?.kind!=='deal'||!['hold','reserved','contracting','committed'].includes(e.status)||termination(e))bad('No eligible deal or review already open.');output=add('termination','Termination · '+e.title,'under_review',{reason:say(d.reason,'Reason'),proposedBy:a!.id,legal:null,finance:null},e.projectId!,e.id,a!.id);break;}
 case 'termination.review':{role('legal','finance');if(e?.kind!=='termination'||e.status!=='under_review')bad('Select an open case.');e.data[a!.role]={actorId:a!.id,evidence:say(d.reason,'Evidence'),at:now};bump(e);break;}
 case 'termination.release':{role('manager');if(e?.kind!=='termination'||e.status!=='under_review'||!e.data.legal||!e.data.finance)bad('Finance and Legal must review before release.');const z=rel(e);if(s.entities.some(q=>q.kind==='document'&&q.dealId===z.id&&['out_for_signature','partially_signed'].includes(q.status)))bad('Cancel the live signing process with evidence first.');e.data.releaseEvidence=say(d.reason,'Evidence claim ended');e.status='released';bump(e);z.status='terminated';bump(z);for(const q of items(z)){q.data.endedAt=now;q.status='ended';bump(q);const unit=get(q.data.itemId,'inventory',false);unit.status='withdrawn';bump(unit)}break;}
 case 'milestone.publish':{role('delivery','manager');if(e?.kind!=='milestone'||!['completed','in_progress'].includes(e.status))bad('Complete the milestone first.');e.status='published';e.data.actualAt=now;e.data.evidence=say(d.reason,'Completion evidence');bump(e);break;}
 case 'change.create':{role('buyer','delivery','manager');const z=get(d.dealId,'deal');if(z.status==='completed')bad('Completed sales require a correction case.');output=add('change',say(d.title,'Change title'),'requested',{description:say(d.description,'Description'),amountCents:0,revision:1},z.projectId!,z.id,a!.id);break;}
 case 'change.price':{role('delivery');if(e?.kind!=='change'||e.status!=='requested')bad('Change is not awaiting pricing.');e.data.amountCents=pos(d.amountCents);e.data.feasibility=say(d.reason,'Feasibility evidence');e.status='priced';bump(e);break;}
 case 'change.accept':{role('buyer');if(e?.kind!=='change'||e.status!=='priced'||!rel(e).data.partyActorIds.includes(a!.id))bad('This priced change is not available to you.');e.status='buyer_accepted';e.data.acceptedRevision=e.data.revision;e.data.acceptedBy=a!.id;bump(e);break;}
 case 'change.approve':{role('manager');if(e?.kind!=='change'||e.status!=='buyer_accepted'||e.data.acceptedRevision!==e.data.revision)bad('Buyer acceptance of the current version is required.');const z=rel(e);e.status='approved';e.data.approvedAt=now;bump(e);z.data.priceCents+=e.data.amountCents;invalidate(z);add('schedule','Approved change','active',{amountCents:e.data.amountCents,currency:z.data.currency,dueAt:null,gate:'completion',changeId:e.id},e.projectId!,e.dealId);break;}
 case 'inspection.create':{role('delivery');const z=get(d.dealId,'deal');output=add('inspection','Inspection · '+z.title,'completed',{rooms:say(d.rooms,'Rooms'),checks:say(d.checks,'Checks'),criticalDefects:!!d.criticalDefects,inspectedAt:now},z.projectId!,z.id,a!.id);z.data.technicalReady=false;bump(z);break;}
 case 'deal.ready':{role('delivery');if(e?.kind!=='deal')bad('Select a deal.');const checks=s.entities.filter(x=>x.kind==='inspection'&&x.dealId===e.id);if(!checks.length||checks.at(-1)!.data.criticalDefects)bad('A completed inspection without critical defects is required.');e.data.technicalReady=true;e.data.readinessEvidence=say(d.reason,'Technical evidence');bump(e);break;}
 case 'deal.finance_approve':{role('finance');if(e?.kind!=='deal'||e.status!=='committed'||due(e,'completion'))bad('Binding sale and full verified balance required.');e.data.financeApproval={at:now,actorId:a!.id,priceCents:e.data.priceCents,evidence:say(d.reason,'Finance evidence')};bump(e);break;}
 case 'deal.legal_approve':{role('legal');if(e?.kind!=='deal'||e.status!=='committed'||termination(e))bad('Resolve legal blockers first.');e.data.legalCompletion={at:now,actorId:a!.id,priceCents:e.data.priceCents,evidence:say(d.reason,'Formalities evidence')};bump(e);break;}
 case 'deal.complete':{role('manager');if(e?.kind!=='deal'||e.status!=='committed'||!e.data.binding||termination(e)||due(e,'completion')||e.data.financeApproval?.priceCents!==e.data.priceCents||e.data.legalCompletion?.priceCents!==e.data.priceCents)bad('Binding, current Finance/Legal approvals and all payments are required.');e.status='completed';e.data.completedAt=now;bump(e);for(const q of items(e)){q.status='completed';bump(q)}for(const q of s.entities.filter(x=>x.kind==='commission'&&x.dealId===e.id)){q.status='eligible';bump(q)}break;}
 case 'handover.create':{role('delivery');const z=get(d.dealId,'deal');output=add('handover','Handover · '+z.title,'planned',{scheduledAt:when(d.scheduledAt),participants:say(d.participants,'Participants')},z.projectId!,z.id,a!.id);break;}
 case 'handover.confirm':{role('delivery');if(e?.kind!=='handover'||e.status!=='planned')bad('Select a planned handover.');e.status='confirmed';bump(e);break;}
 case 'handover.complete':{role('delivery');if(e?.kind!=='handover'||e.status!=='confirmed')bad('Confirm the appointment first.');const z=rel(e);if(z.status!=='completed'||!z.data.technicalReady||termination(z)||due(z,'completion'))bad('Sale, finance and technical readiness are required before keys.');if(!['accepted','accepted_with_defects','refused'].includes(d.outcome))bad('Choose an outcome.');e.data.outcome=d.outcome;e.data.meters=say(d.meters,'Meter readings');e.data.keys=say(d.keys,'Keys');e.data.evidence=say(d.reason,'Protocol evidence');e.status=d.outcome==='refused'?'refused':'completed';e.data.completedAt=now;bump(e);if(e.status==='completed'){z.data.handedOverAt=now;bump(z)}else task('Arrange new handover',z,'delivery');break;}
 case 'service.create':{role('buyer','care','delivery','property_manager');const p=project(d.projectId),z=d.dealId?get(d.dealId,'deal'):null;if(a!.role==='buyer'&&(!z||!z.data.partyActorIds.includes(a!.id)))bad('Select your property.',403);if(a!.role==='property_manager'&&z)bad('Your scope is shared areas only.',403);output=add('service',say(d.title,'Issue title'),'new',{unitId:z?.data.unitId||null,location:say(d.location,'Location'),description:say(d.description,'Description',1500),priority:d.priority==='critical'?'critical':'normal',reporterId:a!.id,dueAt:later(2,Date.parse(now))},p.id,z?.id,'care');task('Review new issue',output,'care');break;}
 case 'service.review':{role('care');if(e?.kind!=='service'||!['new','needs_information','closed','declined','awaiting_verification'].includes(e.status))bad('Select a reviewable case.');if(['closed','declined'].includes(e.status))e.data.reopenReason=say(d.reason,'Reopening reason');e.status='under_review';bump(e);break;}
 case 'service.decide':{role('care');if(e?.kind!=='service'||e.status!=='under_review'||!['approved','declined','needs_information'].includes(d.status))bad('Review the case and choose a decision.');e.status=d.status;e.data.decisionReason=say(d.reason,'Decision reason');bump(e);break;}
 case 'service.assign':{role('care');if(e?.kind!=='service'||!['approved','assigned','scheduled','in_progress','awaiting_verification'].includes(e.status))bad('Approve the case first.');const worker=s.actors.find(x=>x.id===d.contractorId&&x.role==='contractor'&&x.active&&x.projectIds.includes(e!.projectId!));if(!worker)bad('Choose an active contractor for the project.');for(const j of s.entities.filter(x=>x.kind==='work_order'&&x.data.serviceId===e.id&&!['declined','reassigned'].includes(x.status))){j.status='reassigned';bump(j)}output=add('work_order',e.title,'offered',{serviceId:e.id,scope:say(d.scope,'Work scope'),accessConfirmed:false,contactName:'Customer care',contactPhone:'Contact the project team'},e.projectId!,e.dealId,worker!.id,e.id);e.status='assigned';bump(e);break;}
 case 'job.accept':case 'job.decline':{role('contractor');if(e?.kind!=='work_order'||e.ownerId!==a!.id||e.status!=='offered')bad('Only your offered job can be changed.');e.status=action==='job.accept'?'accepted':'declined';if(e.status==='declined'){e.data.reason=say(d.reason,'Decline reason');const z=get(e.data.serviceId,'service',false);z.status='approved';bump(z);task('Reassign declined job',z,'care')}bump(e);break;}
 case 'job.schedule':{role('contractor','care');if(e?.kind!=='work_order'||e.status!=='accepted'||a!.role==='contractor'&&e.ownerId!==a!.id)bad('The assigned contractor must accept the job.');if(d.accessConfirmed!==true)bad('Confirm access with the resident.');e.data.scheduledAt=when(d.scheduledAt);e.data.accessConfirmed=true;e.data.accessEvidence=say(d.reason,'Access agreement');e.status='scheduled';bump(e);const z=get(e.data.serviceId,'service',false);z.status='scheduled';bump(z);break;}
 case 'job.start':{role('contractor');if(e?.kind!=='work_order'||e.ownerId!==a!.id||e.status!=='scheduled'||!e.data.accessConfirmed)bad('Confirm a scheduled visit first.');e.status='in_progress';e.data.startedAt=now;bump(e);const z=get(e.data.serviceId,'service',false);z.status='in_progress';bump(z);break;}
 case 'job.submit':{role('contractor');if(e?.kind!=='work_order'||e.ownerId!==a!.id||e.status!=='in_progress')bad('Start your assigned job first.');const proof=get(d.evidenceId,'document');if(proof.parentId!==e.id||!['image/jpeg','image/png','image/webp'].includes(proof.data.mime))bad('Upload a completion photo for this job.');e.data.completionNote=say(d.reason,'Work summary');e.data.evidenceId=proof.id;e.status='awaiting_verification';bump(e);const z=get(e.data.serviceId,'service',false);z.status='awaiting_verification';bump(z);task('Verify completed repair',z,'care');break;}
 case 'service.owner_response':{role('buyer');if(e?.kind!=='service'||e.status!=='awaiting_verification'||!rel(e).data.partyActorIds.includes(a!.id))bad('No repair awaits your response.');if(!['confirmed','disputed'].includes(d.response))bad('Choose a response.');e.data.ownerResponse={response:d.response,actorId:a!.id,note:say(d.reason,'Feedback'),at:now};if(d.response==='disputed')e.status='under_review';bump(e);break;}
 case 'service.close':{role('care');if(e?.kind!=='service'||e.status!=='awaiting_verification'||e.data.ownerResponse?.response==='disputed')bad('Verify the contractor’s evidence and owner response.');if(e.data.ownerResponse?.response!=='confirmed'){e.data.followup={contactAttempts:say(d.contactAttempts,'Contact attempts'),inspection:say(d.followupInspection,'Follow-up inspection'),actorId:a!.id}}e.data.verification=say(d.reason,'Verification evidence');e.status='closed';e.data.closedAt=now;bump(e);break;}
 case 'task.complete':{if(e?.kind!=='task'||e.ownerId!==a!.id&&a!.role!=='manager')bad('This task is not assigned to you.');e.status='completed';e.data.completedAt=now;bump(e);break;}
 case 'message.send':{const p=project(d.projectId);const audience=a!.role==='buyer'?'buyer':a!.role==='agent'?'agent':a!.role==='contractor'?'contractor':['internal','buyer','agent','all_parties'].includes(d.audience)?d.audience:'internal';if(d.dealId)get(d.dealId,'deal');output=add('message','Message','sent',{body:say(d.body,'Message',2500),audience,authorName:a!.name},p.id,d.dealId,a!.id,d.parentId);break;}
 case 'website.save':case 'website.publish':{role('manager');if(e?.kind!=='project')bad('Select a project.');if(action==='website.save')e.data.websiteDraft=say(d.content,'Project description',2500);else{if(!e.data.websiteDraft)bad('Save a draft first.');e.data.websitePublished=e.data.websiteDraft;e.data.websiteVersion++;e.data.published=true}bump(e);break;}
 case 'inventory.price':case 'inventory.release':{role('manager');if(e?.kind!=='inventory')bad('Select inventory.');if(action==='inventory.release'){if(!['released','withdrawn','unreleased'].includes(d.status))bad('Choose a release mode.');e.status=d.status}else{e.data.priceHistory=[...(e.data.priceHistory||[]),{priceCents:e.data.priceCents,version:e.data.priceVersion,at:now}];e.data.priceCents=pos(d.priceCents);e.data.priceVersion++}bump(e);break;}
 case 'refund.request':{role('finance');if(e?.kind!=='payment'||e.status!=='confirmed')bad('Select a confirmed receipt.');output=add('refund','Refund request','requested',{paymentId:e.id,amountCents:pos(d.amountCents),reason:say(d.reason,'Reason'),proposedBy:a!.id},e.projectId!,e.dealId,a!.id);break;}
 case 'refund.approve':{role('finance');if(e?.kind!=='refund'||e.status!=='requested'||e.data.proposedBy===a!.id)bad('Another Finance person must approve.');e.status='approved';e.data.approvedBy=a!.id;bump(e);break;}
 case 'grant.revoke':{role('admin');if(e?.kind!=='grant'||e.organizationId!==a!.organizationId)bad('Only the project owner can revoke access.');const who=s.actors.find(x=>x.id===e.data.actorId);if(!who||who.id===a!.id||who.role==='admin'&&s.actors.filter(x=>x.role==='admin'&&x.active&&x.organizationId===a!.organizationId).length===1)bad('Keep at least one active administrator.');e.status='revoked';who!.active=false;bump(e);for(const t of s.entities.filter(x=>x.kind==='task'&&x.ownerId===who!.id&&x.status==='open')){t.ownerId='manager';bump(t)}break;}
 case 'refund.execute':{
  role('finance');if(e?.kind!=='refund'||e.status!=='approved')bad('Approve the refund with a second Finance person first.');
  const payment=get(e.data.paymentId,'payment'),amount=pos(e.data.amountCents);
  if(amount>payment.data.amountCents-(payment.data.refundedCents||0))bad('Refund exceeds the remaining receipt.');
  const reference=say(d.reference,'External refund reference',100),evidence=say(d.reason,'Bank execution evidence');
  if(s.entities.some(x=>x.kind==='payment'&&x.data.reference===reference&&x.data.accountId===payment.data.accountId))bad('This bank reference is already recorded.');
  const paid=s.entities.filter(x=>x.kind==='payment_allocation'&&x.status==='active'&&x.data.paymentId===payment.id);
  const used=paid.reduce((n,x)=>n+x.data.amountCents,0),credit=payment.data.amountCents-(payment.data.refundedCents||0)-used;
  let toReverse=Math.max(0,amount-credit);
  for(const allocation of [...paid].reverse()){
   if(!toReverse)break;const take=Math.min(toReverse,allocation.data.amountCents),remainder=allocation.data.amountCents-take;
   allocation.status='reversed';allocation.data.reversalReason='Refund '+e.id;allocation.data.reversedAt=now;bump(allocation);
   if(remainder)add('payment_allocation','Allocation after refund','active',{paymentId:payment.id,scheduleId:allocation.data.scheduleId,amountCents:remainder,correctsId:allocation.id},e.projectId!,e.dealId,a!.id);
   toReverse-=take;
  }
  payment.data.refundedCents=(payment.data.refundedCents||0)+amount;bump(payment);
  const movement=add('payment','Refund · '+reference,'confirmed',{amountCents:amount,currency:payment.data.currency,direction:'refund',originalPaymentId:payment.id,refundId:e.id,reference,accountId:payment.data.accountId,evidence,confirmedBy:a!.id,receivedAt:now},e.projectId!,e.dealId,a!.id);
  e.status='executed';e.data.movementId=movement.id;e.data.executedAt=now;bump(e);invalidate(rel(e));task('Review balance after refund',rel(e),'finance',0);break;
 }
 case 'commission.approve':{role('finance');if(e?.kind!=='commission'||e.status!=='eligible')bad('The commission milestone is not met.');e.status='approved';e.data.approvedBy=a!.id;bump(e);break;}
 case 'commission.pay':{role('finance');if(e?.kind!=='commission'||!['approved','partially_paid'].includes(e.status))bad('Approve commission first.');const amount=pos(d.amountCents),paid=s.entities.filter(x=>x.kind==='commission_payment'&&x.parentId===e.id).reduce((n,x)=>n+x.data.amountCents,0);if(paid+amount>e.data.amountCents)bad('Commission payment exceeds the approved balance.');add('commission_payment','Commission payment','confirmed',{amountCents:amount,currency:e.data.currency,reference:say(d.reference,'Payment reference'),evidence:say(d.reason,'Bank evidence'),recipientId:e.data.recipientId},e.projectId!,e.dealId,a!.id,e.id);e.status=paid+amount===e.data.amountCents?'paid':'partially_paid';bump(e);break;}
 case 'appointment.create':{role('sales','manager','agent','delivery');const p=project(d.projectId),start=when(d.startsAt),end=when(d.endsAt);if(end<=start)bad('End must be after start.');output=add('appointment',say(d.title,'Appointment title'),'requested',{startsAt:start,endsAt:end,resource:say(d.resource,'Resource'),type:'viewing',contactId:d.contactId||null},p.id,undefined,a!.id);break;}
 case 'appointment.confirm':{role('sales','manager','delivery');if(e?.kind!=='appointment'||e.status!=='requested')bad('Choose a requested appointment.');if(s.entities.some(x=>x.kind==='appointment'&&x.id!==e.id&&x.status==='confirmed'&&(x.ownerId===e.ownerId||x.data.resource===e.data.resource)&&x.data.startsAt<e.data.endsAt&&x.data.endsAt>e.data.startsAt))bad('The person or resource has a confirmed appointment at this time.',409);e.status='confirmed';bump(e);break;}
 case 'appointment.finish':{role('sales','manager','delivery');if(e?.kind!=='appointment'||!['requested','confirmed'].includes(e.status)||!['completed','cancelled','no_show'].includes(d.status))bad('Choose a valid appointment outcome.');e.status=d.status;e.data.outcomeNote=say(d.reason,'Outcome note');bump(e);task('Follow up after appointment',e,e.ownerId||a!.id);break;}
 case 'notification.read':{if(e?.kind!=='notification'||e.ownerId!==a!.id)bad('Notification unavailable.',403);e.status='read';bump(e);break;}
 default:bad('Action is not supported.');
 }
 for(const q of s.entities.filter(x=>x.kind==='allocation'&&!x.data.endedAt)){if(s.entities.some(z=>z.id!==q.id&&z.kind==='allocation'&&!z.data.endedAt&&z.data.itemId===q.data.itemId))bad('Inventory allocation conflict.',409)}
 return {state:s,id:output?.id||'',message:'Saved successfully.'};
}
const later=(days:number,t=Date.now())=>new Date(t+days*86400000).toISOString();
